apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-test
spec:
  replicas: 10
  selector:
    matchLabels:
      chapter: services
  template:
    metadata:
      labels:
        chapter: services
    spec:
      containers:
      - name: hello-ctr
        image: crpi-gw6w9nvclnqq4rxd.cn-shanghai.personal.cr.aliyuncs.com/dev_rh/k8sbook:1.0
        ports:
        - containerPort: 8080
